CREATE DATABASE IF NOT EXISTS esun_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE esun_db;

DROP TABLE IF EXISTS Comment;
DROP TABLE IF EXISTS Post;
DROP TABLE IF EXISTS User;

CREATE TABLE User (
  UserID BIGINT AUTO_INCREMENT PRIMARY KEY,
  UserName VARCHAR(100) NOT NULL,
  Phone VARCHAR(255) NOT NULL UNIQUE,
  Password VARCHAR(512) NOT NULL,
  CoverImage VARCHAR(512),
  Biography TEXT
);

CREATE TABLE Post (
  PostID BIGINT AUTO_INCREMENT PRIMARY KEY,
  UserID BIGINT NOT NULL,
  Content TEXT NOT NULL,
  Image VARCHAR(512),
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE
);

CREATE TABLE Comment (
  CommentID BIGINT AUTO_INCREMENT PRIMARY KEY,
  UserID BIGINT NOT NULL,
  PostID BIGINT NOT NULL,
  Content TEXT NOT NULL,
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE,
  FOREIGN KEY (PostID) REFERENCES Post(PostID) ON DELETE CASCADE
);

